baseURL: "https://kevisc.github.io/" 
title: Kevin Schoenholzer, PhD
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: papers/
          weight: 2

params:
    description: "I am Kevin. My research interest lies in education and socioeconomic stratification using quantitative data analysis."
    author: Kevin Schoenholzer, PhD
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kevin Schoenholzer, PhD
          
          subtitle: "I am currently a Postdoctoral Researcher at the Institute of Communication and Public Policy, University of Lugano (Università della Svizzera italiana, USI) Switzerland, in the research group of Prof. Dr. Benedetto Lepori. My current research primarily investigates how characteristics of higher education institutions and systems influence socioeconomic stratification among graduate populations.<br><br>

  My research addresses: quantitative, longitudinal life-course research focused on social stratification; modeling institutional, individual and regional factors; and comparative analyses exploring how different educational systems and societal ideologies shape diverse life pathways and opportunities across populations.<br><br>

  I have advanced proficiency in statistical modeling and quantitative analysis using R and Stata. I specialize in longitudinal data analysis and comparative international research. <br><br> 
  My academic endeavors aim to provide evidence-based recommendations for education policy that foster social mobility."
          
        
          imageUrl: "headshot.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Kevin Schoenholzer
          buttons:
            - name: Research
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: cv
          url: cv-1.pdf
        - name: Email
          url: mailto:kevin.schoenholzer@usi.ch
          # url: location/
        # - name: Office Hours
        #   url: officehours/
       # - name: Google Scholar
        #  url: https://scholar.google.com/citations?user=K5aOUegAAAAJ&hl
      #  - name: GitHub
        #  url: https://github.com/dacbarbosa
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
      #  - name: Twitter
       #   url: https://twitter.com/barbosa_dac

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kevin"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2